urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}), 
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^ulogin/', include('django_ulogin.urls')), 
    url('^faq/', include('fack.urls')), 
    url(r'^messages/reply/(?P<message_id>[\d]+)/$', 'apps.main.views.message_reply', name='messages_reply_custom'),
    url(r'^messages/apply/(?P<post_id>[\d]+)/$', 'apps.main.views.message_apply', name='messages_apply'),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('apps.main.urls')),
)

apps/main/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User

SEARCH_TARGETS = (
    (0, 'Попутку'), 
    (1, 'Пассажира'), 
    )

GENDERS = (
    (0, 'Мужской'),
    (1, 'Женский')
)

ATTITUDES = (
    (0, 'Отрицательно'),
    (1, 'Нейтрально'),
    (2, 'Терпимо'),
)

TRIP_MODES = (
    (0, 'Регулярно'),
    (1, 'Один раз'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    photo = models.ImageField('Фото', upload_to='static/upload/user_photos', blank=True, null=True)
    gender = models.IntegerField('Пол', choices=GENDERS, max_length=1, default=0)
    age = models.IntegerField('Возраст', blank=True, null=True)

    smoking = models.IntegerField('Оношение к курению', choices=ATTITUDES, default =1)
    music = models.CharField('Музыка', max_length=255, blank=True, null=True)

    phone = models.CharField('Телефон', blank=True, null=True, max_length=255)
    social_network_link = models.CharField('Ссылка на страницу в социальной сети', blank=True, null=True, max_length=255)
    skype_name = models.CharField('Skype', blank=True, null=True, max_length=255)
    icq =  models.CharField('ICQ', blank=True, null=True, max_length=255)

    about = models.TextField('Дополнительная информация', blank=True, null=True)

    class Meta:
        verbose_name='Профайл'
        verbose_name_plural='Профайлы'

    def __unicode__(self):
        return u'{0}({1})'.format(self.user.username, self.pk)

class Post(models.Model):

    search_target = models.IntegerField('Я ищу', max_length=1, choices=SEARCH_TARGETS, default=0 )
    start = models.CharField(db_index=True, max_length=255)
    end = models.CharField(db_index=True, max_length=255)
    # Для обьявлений о поиске пассажира
    places = models.IntegerField('Количество мест', null=True, blank=True)
    cost = models.DecimalField('Стоимость', max_digits=5, decimal_places=2, null=True, blank=True)
    car_info = models.CharField('Описание автомобиля', blank=True, null=True, max_length=255)

    trip_mode = models.IntegerField('График движения', choices=TRIP_MODES, max_length=1, default=0)
    single_departure = models.DateTimeField('Дата отправления (для разовой поездки)', null=True, blank=True)   
    regular_days = models.CharField('Дни недели (для регулярной)', max_length=255, null=True, blank=True)
    regular_departure = models.TimeField('Время отправления (для регулярной)', null=True, blank=True)

    additional_info = models.TextField('Доп инфо', blank=True, null=True)

    author = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    edited_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name= 'Объявление'
        verbose_name_plural='Объявления'

    def __unicode__(self):
        display = u'{0} - {1}'.format(self.start.split(',')[0], self.end.split(',')[0])

        if self.trip_mode == 1:
            display += u' {0}'.format(self.single_departure)
        return display

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)
post_save.connect(create_user_profile, sender=User)


def __unicode__(self):
    if self.get_full_name():
        return self.get_full_name()
    else:
        return self.username

#User.add_to_class("__unicode__", __unicode__)

apps/main/views/profile.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import render

from apps.main.forms import UserProfileForm
from apps.main.models import UserProfile

def view_profile(request, profile_id):
    profile = get_object_or_404(UserProfile, pk=profile_id)
    return render(request, 'profiles/profile.html', {'profile':profile})

@login_required
def update_profile(request):
    profile = get_object_or_404(UserProfile, pk=request.user.get_profile().pk)
    if request.method == 'GET':
        return render(request, 'profiles/form.html', {'form':UserProfileForm(instance=profile),})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse(view_profile, kwargs={'profile_id':profile.pk}))

@login_required
@require_POST
def update_avatar(request):
    profile = get_object_or_404(UserProfile, pk=request.user.get_profile().pk)
    if request.FILES:
        profile.photo = request.FILES['avatar']
        profile.save()
        return HttpResponse(profile.photo.url, status=200)
    if request.POST.get('clear_avatar', None):
        profile.photo = None
        profile.save()
        return HttpResponse('static/img/default_user.png', status=200)

templates/profiles/form.html
{% extends "base.html" %}
{% load i18n %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}css/account.css"/>
{% endblock %}

{% block js_extra %}
<script type="text/javascript" src="{{ STATIC_URL }}3party/jquery.form.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/profile.js"></script>
{% endblock %}

{% block content %}
<div id="profile_view" class="account_content">
  <h1>
    <a href="{% url "view_profile" profile_id=request.user.get_profile.pk %}" class="button orange">
      {% trans "Отмена" %}
    </a>
    {% trans "Профиль пользователя" %}
  </h1>

    <div class="clearfix profile-first">
      <div class="col">
        <img class="profile_avatar" width="165" height="165" src="{% if form.instance.photo %}/{{ form.instance.photo.url }}{% else %}{{ STATIC_URL }}img/default_user.png {% endif %}" />
        <form method="POST" action="{% url "update_avatar" %}" enctype="multipart/form-data" id="image-form">
          {% csrf_token %}
          <a class="button orange change_avatar" href="#">
            {% trans "Изменить" %}
          </a>
          <a class="button grey delete_avatar" href="#">
            {% trans "Удалить" %}
          </a>
          <input type="file" name="avatar" class="hidden_fileinput" />
        </form>
      </div>
      <form method="POST" action="" enctype="multipart/form-data" >
        {% csrf_token %}
      <div class="col">
        <h3>{{ form.first_name }}  {{ form.last_name }}</h3>
        <ul class="info">
          <li>
            <span class="label">{% trans "Пол:" %}</span>
            <span class="value">{{ form.gender }}</span>
          </li>
          <li>
            <span class="label">{% trans "Возраст:" %}</span>
            <span class="value">{{ form.age }}</span>
          </li>
          <li>
            <span class="label">{% trans "Отношение к курению:" %}</span>
            <span class="value">{{ form.smoking }}</span>
          </li>
          <li>
            <span class="label">{% trans "Музыка:" %}</span>
            <span class="value">{{ form.music }}</span>
          </li>
        </ul>
      </div>
    </div>

    <div class="clearfix">
      <h2>{% trans "Контакты" %}</h2>
      <ul class="info">
        <li>
          <span class="label">{% trans "Телефон:" %}</span>
          <span class="value">{{ form.phone }}</span>
        </li>
        <li>
          <span class="label">{% trans "e-mail:" %}</span>
          <span class="value">{{ form.email }}</span>
        </li>
        <li>
          <span class="label">{% trans "Страница в соц. сети:" %}</span>
          <span class="value">{{ form.social_network_link }}</span>
        </li>
        <li>
          <span class="label">{% trans "skype:" %}</span>
          <span class="value">{{ form.skype_name }}</span>
        </li>
        <li>
          <span class="label">{% trans "ICQ:" %}</span>
          <span class="value">{{ form.icq }}</span>
        </li>
      </ul>
    </div>
    <div class="clearfix">
      <h2>{% trans "Дополнительная информация" %}</h2>
      <p>{{ form.about }}</p>
    </div>
    <div class="clearfix">
      <input type="submit" value="{% trans 'Сохранить' %}" class="button green big" />
    </div>
  </form>
</div>
{% endblock %}

templates/profiles/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}css/account.css"/>
{% endblock %}

{% block content %}
<div id="profile_view" class="account_content">
  <h1>
    {% if profile.pk == request.user.get_profile.pk %}
    <a class="button orange" href="{% url "update_profile" %}">{% trans "Редактировать" %} </a>
    {% endif %}
    {% trans "Профиль пользователя" %} 
  </h1>
  <div class="clearfix">
    <div class="col">
      <img width="150" height="150" src="{% if profile.photo %}/{{ profile.photo.url }}{% else %}{{ STATIC_URL }}img/default_user.png {% endif %}" />
    </div>
    <div class="col" style="float:none;">
      <h3>{{ profile.user.first_name }}  {{ profile.user.last_name }}</h3>
      <ul class="info">
        <li>
          <span class="label">{% trans "Пол:" %}</span>
          <span class="value">{{ profile.get_gender_display }}</span>
        </li>
        <li>
          <span class="label">{% trans "Возраст:" %}</span>
          <span class="value">{{ profile.age|default_if_none:"&nbsp;" }}</span>
        </li>
        <li>
          <span class="label">{% trans "Отношение к курению:" %}</span>
          <span class="value">{{ profile.get_smoking_display }}</span>
        </li>
        <li>
          <span class="label">{% trans "Музыка:" %}</span>
          <span class="value">{{ profile.music|default_if_none:"&nbsp;" }}</span>
        </li>
      </ul>
    </div>
  </div>

  <div class="clearfix">
    <h2>{% trans "Контакты" %}</h2>
    <ul class="info">
      <li>
        <span class="label">{% trans "Телефон:" %}</span>
        <span class="value">{{ profile.phone|default_if_none:"&nbsp;" }}</span>
      </li>        
      <li>
        <span class="label">{% trans "e-mail:" %}</span>
        <span class="value"><a href="mailto:{{ profile.user.email }}">{{ profile.user.email }}</a></span>
      </li>        
      <li>
        <span class="label">{% trans "Страница в соц. сети:" %}</span>
        <span class="value">
          {% if profile.social_network_link != none %}
          <a href="{{ profile.social_network_link }}" target="blank">
            {{ profile.social_network_link }}
          </a >
          {% endif %}
        </span>
      </li>        
      <li>
        <span class="label">{% trans "skype:" %}</span>
        <span class="value">{{ profile.skype_name|default_if_none:"&nbsp;" }}</span>
      </li>        
      <li>
        <span class="label">{% trans "ICQ:" %}</span>
        <span class="value">{{ profile.icq|default_if_none:"&nbsp;" }}</span>
      </li>        
    </ul>
  </div>
  <div class="clearfix">
    <h2>{% trans "Дополнительная информация" %}</h2>
    <p>
      <span style="font-size:36px">&#147;</span>
      {{ profile.about|default_if_none:"&nbsp;" }}
      <span style="font-size:36px">&#148;</span>
    </p>
  </div>
</div>
{% endblock %}